In [118]:
import pandas as pd
import numpy as np
from nltk.tokenize import regexp_tokenize
from nltk import pos_tag
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from gensim.models import Word2Vec
from datetime import datetime, timedelta
import time
import pickle

In [7]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\fergu\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [14]:
import nltk
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\fergu\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.

True

In [21]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\fergu\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\wordnet.zip.

True

In [17]:
wnl = WordNetLemmatizer()

def func_lemmatize(words):
    lemmatized = []
    for word, tag in pos_tag(words):
        wntag = tag[0].lower()
        wntag = wntag if wntag in ['a','r','n','v'] else None
        
        lemma = wnl.lemmatize(word,wntag) if wntag else word
        lemmatized.append(lemma)
    return lemmatized

stop = set(stopwords.words('english'))

pattern = r'(\w+)'

In [127]:
# 11:37
#df = pd.read_csv('all-the-news-2-1.csv')
tab = pd.read_csv('labeled_data.csv')
tab.head()

,Unnamed: 0,count,hate_speech,offensive_language,neither,class,tweet
0,0,3,0,0,3,2,!!! RT @mayasolovely: As a woman you shouldn't...
1,1,3,0,3,0,1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2,2,3,0,3,0,1,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3,3,3,0,2,1,1,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4,4,6,0,6,0,1,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...

In [128]:
tab.shape

(24783, 7)

In [76]:
tab = pd.DataFrame({'article':['If the good guys are smart, this is the moment they swoop in and arrest everyone.',
                               'Did you make it to the Allen & Co conference in Sun Valley, Idaho this past week?',
                              'A pandemic era box office bonanza for Marvel’s Black Widow put a spring in Disney’s step today, though it hasn’t quite translated to gains for cinemas;',
                              'This latest update, along with projections of positive economic growth, was met with notable optimism from the White House and record highs on Wall Street.',
                              'In midst of this uneven recovery, and perhaps somewhat counterintuitively, others have noticed another pattern that may further elevate unemployment rates in the months to come:',
                              'people are leaving their jobs.']})

In [77]:
tab

                                             article
0  If the good guys are smart, this is the moment...
1  Did you make it to the Allen & Co conference i...
2  A pandemic era box office bonanza for Marvel’s...
3  This latest update, along with projections of ...
4  In midst of this uneven recovery, and perhaps ...
5                     people are leaving their jobs.

In [73]:
#df = df[:3]

In [129]:
tab['article_words'] = [regexp_tokenize(article,pattern) for article in tab['tweet']]
tab['article_words'] = [[word for word in article if word.isalpha()] for article in tab['article_words']]
tab['article_words'] = [func_lemmatize(article) for article in tab['article_words']]
tab['article_words'] = [[word.lower() for word in article if word.lower() not in stop] for article in tab['article_words']]

In [130]:
tab

,Unnamed: 0,count,hate_speech,offensive_language,neither,class,tweet,article_words
0,0,3,0,0,3,2,!!! RT @mayasolovely: As a woman you shouldn't...,"[rt, mayasolovely, woman, complain, clean, hou..."
1,1,3,0,3,0,1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...,"[rt, boy, dat, cold, tyga, dwn, bad, cuffin, d..."
2,2,3,0,3,0,1,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...,"[rt, urkindofbrand, dawg, rt, ever, fuck, bitc..."
3,3,3,0,2,1,1,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...,"[rt, look, like, tranny]"
4,4,6,0,6,0,1,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...,"[rt, shenikaroberts, shit, hear, might, true, ..."
...,...,...,...,...,...,...,...,...
24778,25291,3,0,2,1,1,you's a muthaf***in lie &#8220;@LifeAsKing: @2...,"[muthaf, lie, lifeasking, right, tl, trash, mi..."
24779,25292,3,0,1,2,2,"you've gone and broke the wrong heart baby, an...","[go, break, wrong, heart, baby, drive, redneck..."
24780,25294,3,0,3,0,1,young buck wanna eat!!.. dat nigguh like I ain...,"[young, buck, wanna, eat, dat, nigguh, like, a..."
24781,25295,6,0,6,0,1,youu got wild bitches tellin you lies,"[youu, get, wild, bitch, tellin, lie]"
24782,25296,3,0,0,3,2,~~Ruffled | Ntac Eileen Dahlia - Beautiful col...,"[ruffled, ntac, eileen, dahlia, beautiful, col..."

In [64]:
tab['article_words'] = [regexp_tokenize(article,pattern) for article in tab['article']]
tab

                  article                 article_words
0  hello, how are you 99?    [hello, how, are, you, 99]
1      *What* is going on         [What, is, going, on]
2  we are doing a project  [we, are, doing, a, project]

In [65]:
tab['article_words'] = [[word for word in article if word.isalpha()] for article in tab['article_words']]
tab

                  article                 article_words
0  hello, how are you 99?        [hello, how, are, you]
1      *What* is going on         [What, is, going, on]
2  we are doing a project  [we, are, doing, a, project]

In [66]:
tab['article_words'] = [func_lemmatize(article) for article in tab['article_words']]
tab

                  article             article_words
0  hello, how are you 99?     [hello, how, be, you]
1      *What* is going on        [What, be, go, on]
2  we are doing a project  [we, be, do, a, project]

In [81]:
df

,Unnamed: 0,Unnamed: 0.1,date,year,month,day,author,title,article,url,section,publication
0,0,0,2016-12-09 18:31:00,2016,12.0,9,Lee Drutman,We should take concerns about the health of li...,"This post is part of Polyarchy, an independent...",https://www.vox.com/polyarchy/2016/12/9/138983...,NaN,Vox
1,1,1,2016-10-07 21:26:46,2016,10.0,7,Scott Davis,Colts GM Ryan Grigson says Andrew Luck's contr...,The Indianapolis Colts made Andrew Luck the h...,https://www.businessinsider.com/colts-gm-ryan-...,NaN,Business Insider
2,2,2,2018-01-26 00:00:00,2018,1.0,26,NaN,Trump denies report he ordered Mueller fired,"DAVOS, Switzerland (Reuters) - U.S. President ...",https://www.reuters.com/article/us-davos-meeti...,Davos,Reuters

In [3]:
df.shape

(2688879, 12)

In [5]:
df.loc[120,'article']

'Raúl Ortega Ayala’s new exhibition at Proyectos Monclova includes a buffet based on a historical image of the restaurant atop the World Trade Center and a model of the Tower of Babel sculpted out of lard. Advertise on Hyperallergic with Nectar Ads MEXICO CITY — A scene from a grotesque flesh ritual is acted out in the main gallery of Raúl Ortega Ayala’s Food for Thought, a show revealing humanity’s incredible capacity to consume. It might ruin your appetite, but beneath the drama there are layers of subtlety and nuance in the video works and installation. The works, which span the top floor and the basement galleries of Proyectos Monclova, are part of the same series but comprise distinct projects dealing with consumption and food in two different ways. The artist connects\xa0consumption habits to ceremony, debauchery, and the decline of society. The video works on the top floor deal directly with food culture through a style of artistic-anthropological study, which marks the culmination of\xa0three years of research for Ortega Ayala. Three videos are accompanied by two small paintings tucked into the corners of the installation, leaving the main gallery mostly dark. Amid the darkness, three warm floodlights illuminate “Babel Fat Tower” (2010), a contemporary nod to Pieter Bruegel’s masterpiece.\xa0An actual\xa0tower of lard, the sculpture emits a subtle stench as the lights heat the glistening pile, which\xa0is intended to melt down over the course of the exhibition.\xa0The metaphor isn’t exactly subtle, but the stinking pile loans a meaty materiality to the cold video installation nearby. Alongside the large video projections, the\xa0small paintings don’t call attention to themselves. They are inspired by foie gras and stuffed pig, except that the overfed animals\xa0in these images are represented by human hands making shadow puppets, and they allude to another motif\xa0that echoes throughout the show — the performance of food. They also reveal the painter in Ortega Ayala. This painterliness reemerges in the videos, where the artist frames human figures in compositions reminiscent of a Rembrandt, emphasizing the fleshy\xa0body and packing the frame with a tangle of limbs and saturated colors. The pair of\xa0projections\xa0in the main gallery space make up the\xa0two-channel video work, “Tomatina-Tim” (2016). On one screen, Ortega Ayala films the annual La Tomatina festival in Buñol, Spain from above, its many participants\xa0dissolving into a sweaty mass of bodies covered in blood-red tomato juice and flesh. Despite the festive atmosphere and the zealous roar of a thousand drunken bros, the drama turns dark and sad when the tomatoes run out and the crowd disperses, leaving\xa0people strewn about, sitting or lying in the wet trash. The noise of the crowd dies down and a woman’s scream is identifiable amid the din. Then we see her on the screen, surrounded by a throng of shirtless men trying to rip her shirt off — apparently part of the tradition of the festival, as seen during the peak of the tomato\xa0mashing madness, but the assault and the woman’s desperation are palpable. On the opposite screen, a hotdog-eating champion and professional gurgitator named Tim sits down casually to a pile of a few dozen hotdogs at the famous restaurant Nathan’s, smashing them into his mouth two at a time and soaking the buns in water so that they slide\xa0down his throat more easily. This training routine of excess epitomizes something pathological in our culture of consumption, where satiation is never possible. Part of Ortega Ayala’s intention is to underline the ridiculous pointlessness of these ceremonies, whose only purposes\xa0are\xa0indulging gluttony and celebrating excess — how appropriately and sickeningly poignant. The festival of debauchery and wasted food in Spain bears the markings of an ancient pagan fertility ritual, but there is no higher meaning here, as Kim Córdova points out in the exhibition text. Are there\xa0traditions of excess,\xa0or does gluttony itself fill the void left by a lack of tradition? Another video on view, “Untitled (Cheese Rolling)” (2017), documents the flailing, tumbling, tangled participants of the now world-famous\xa0festival in\xa0Gloucestershire, England, where participants race down a steep hill in pursuit\xa0of a tumbling wheel of cheese, resulting in a variety of totally avoidable blunt trauma injuries.\xa0The slow motion video shows the martyrdom\xa0of the townspeople\xa0willing to sacrifice\xa0themselves\xa0in the name of decontextualized tradition. There is a deeper metaphor about ‘biting the hand that feeds you’ suggested by Ortega Ayala’s work downstairs. In the main gallery, a very strange scene awaits. A feast has been prepared, based on a vintage\xa0image of a buffet at the Windows on the World restaurant, which served clients atop the North Tower\xa0of the original World Trade Center. This\xa0powerful evocation\xa0of September 11 gave way to a shared\xa0meal during the exhibition opening,\xa0the spread surrounded\xa0by vitrines of images and newspaper clippings documenting the cleanup of the collapsed skyscrapers. The meal’s moldy leftovers remain on display in the gallery.\xa0In the vitrines, Ortega Ayala traces the material of the felled towers to companies in India and China, which purchased the twisted metal as scrap steel in order to make new buildings, housewares, or maybe even weapons. The common practice of recycling scrap steel is suddenly complicated by tragedy and the enormous, all-encompassing cycle of destruction and construction. In Food for Thought, Ortega Ayala attempts to\xa0connect modern practices of gluttony with their possible origins in\xa0tradition or ritual, but the result is an expression of some primitive desire of the flesh to get drunk and dirty. The\xa0image of the mythical tower turned into an homage to lard alludes\xa0to our corrupted best intentions to reach toward the heavens. The artist\xa0portrays modernity, through the recycling of an unimaginably destructive tragedy,\xa0as the\xa0evolution\xa0of our attempts\xa0to clean up the mess from the\xa0trial and error of building (and rebuilding) civilization. Raul Ortega Ayala: Food for Thought continues\xa0at Proyectos Monclova (Colima 55, Roma Norte, Mexico City) through\xa0June 10.'

In [140]:
def create_w2v(col1,col2,max_epochs,vec_size,window,min_count,resume=False):
    now  = datetime.now()
    start_time_str = now.strftime('%H:%M:%S')
    print('started at',start_time_str)
        
    start_time = time.time()
    word_list = [[words for words in line] for line in col1]
    unpacked_word_list = [word for line in word_list for word in line]
    
    filename = 'model.sav'
    
    if resume == False:
        model = Word2Vec(col1,vector_size=vec_size,window=window,min_count=min_count,workers=-1)
        model.train(col1,total_examples=len(col1),epochs=max_epochs)
        print('word2vec model has been trained.')
        pickle.dump(model,open(filename,'wb'))
    else:
        file = open(filename,'rb')
        model = pickle.load(file)
        
    averaged_vectors = [] if resume == False else pd.read_csv('intermediate_results.csv',index_col=0)
    
    if resume == True:
        averaged_vectors = [list(averaged_vectors.loc[val,:]) for val in averaged_vectors.index]
    
    j = start_index= len(averaged_vectors)
    if j != 0:
        print(f'{round(j/len(col1),3) * 100}% complete.')
    start_checkpoint_time = time.time()
    
    progress_indicators = []
    
    
    for row in range(j,len(col1)):
        list_of_words = col1[row]
        list_of_vectors = [model.wv[word] for word in list_of_words if unpacked_word_list.count(word) >= min_count]
        avg_vector = np.mean(list_of_vectors,axis=0) if list_of_vectors else np.zeros(vec_size)
        averaged_vectors.append(avg_vector)
#        print(avg_vector)
        
        j += 1
#        print(f'{j} done')
        if j % 1000 == 0:
            intermediate_results = pd.DataFrame(averaged_vectors)
            intermediate_results.to_csv('intermediate_results.csv')
            
        percent_complete = round(j/len(col1) * 100)
        if (percent_complete % 1 == 0) & (percent_complete not in progress_indicators):
            cum_time_raw = (time.time() - start_time)/60
            cum_time = round((time.time() - start_time)/60,1)
            print('{}% complete. Time elapsed: {} min'.format(percent_complete,cum_time))
            progress_indicators.append(percent_complete)
            
            remaining_time = cum_time_raw * (len(col1) - j) / (j - start_index)
            
            est_finish_time = datetime.now() + timedelta(minutes=remaining_time)
            est_finish_time = est_finish_time.strftime('%D:%H:%M:%S')
            print(f'Estimated finish time: {est_finish_time}')
            print('-' * 15)
            
    df_of_vectors = pd.DataFrame(averaged_vectors)
        
    intermediate_table = pd.concat([col2,df_of_vectors],axis=1)
        
    rows_to_remove = [ind for ind in intermediate_table.index if intermediate_table.iloc[ind,2] == 0]
        
    removed_comments = pd.DataFrame(col2[rows_to_remove])
    final_table = intermediate_table.drop(rows_to_remove,axis=0)
        
    interval = round((time.time() - start_time)/60,1)
    print('-' * 25)
    print(f'Finished. That took {interval} min.')
    now = datetime.now()
    end_time_str = now.strftime('%H:%M:%S')
    print(f'Actual finish time: {end_time_str}')
        
    return final_table, removed_comments

In [88]:
tab

,article,article_words
0,"If the good guys are smart, this is the moment...","[good, guy, smart, moment, swoop, arrest, ever..."
1,Did you make it to the Allen & Co conference i...,"[make, allen, co, conference, sun, valley, ida..."
2,A pandemic era box office bonanza for Marvel’s...,"[pandemic, era, box, office, bonanza, marvel, ..."
3,"This latest update, along with projections of ...","[latest, update, along, projection, positive, ..."
4,"In midst of this uneven recovery, and perhaps ...","[midst, uneven, recovery, perhaps, somewhat, c..."
5,people are leaving their jobs.,"[people, leave, job]"

In [141]:
final_table, removed_comments = create_w2v(tab['article_words'],tab['tweet'],10,20,2,5)

started at 17:13:05
word2vec model has been trained.
0% complete. Time elapsed: 0.0 min
Estimated finish time: 07/14/21:02:02:25
---------------
1% complete. Time elapsed: 0.1 min
Estimated finish time: 07/13/21:17:38:13
---------------
2% complete. Time elapsed: 0.4 min
Estimated finish time: 07/13/21:17:37:48
---------------
3% complete. Time elapsed: 0.6 min
Estimated finish time: 07/13/21:17:36:55
---------------
4% complete. Time elapsed: 0.8 min
Estimated finish time: 07/13/21:17:37:12
---------------
5% complete. Time elapsed: 1.1 min
Estimated finish time: 07/13/21:17:37:27
---------------
6% complete. Time elapsed: 1.3 min
Estimated finish time: 07/13/21:17:37:27
---------------
7% complete. Time elapsed: 1.6 min
Estimated finish time: 07/13/21:17:37:26
---------------
8% complete. Time elapsed: 1.8 min
Estimated finish time: 07/13/21:17:37:19
---------------
9% complete. Time elapsed: 2.1 min
Estimated finish time: 07/13/21:17:37:32
---------------
10% complete. Time elapsed: 2.3 min
Estimated finish time: 07/13/21:17:37:21
---------------
11% complete. Time elapsed: 2.5 min
Estimated finish time: 07/13/21:17:36:54
---------------
12% complete. Time elapsed: 2.7 min
Estimated finish time: 07/13/21:17:36:30
---------------
13% complete. Time elapsed: 2.9 min
Estimated finish time: 07/13/21:17:36:13
---------------
14% complete. Time elapsed: 3.1 min
Estimated finish time: 07/13/21:17:35:56
---------------
15% complete. Time elapsed: 3.3 min
Estimated finish time: 07/13/21:17:35:41
---------------
16% complete. Time elapsed: 3.5 min
Estimated finish time: 07/13/21:17:35:27
---------------
17% complete. Time elapsed: 3.7 min
Estimated finish time: 07/13/21:17:35:17
---------------
18% complete. Time elapsed: 3.9 min
Estimated finish time: 07/13/21:17:35:06
---------------
19% complete. Time elapsed: 4.0 min
Estimated finish time: 07/13/21:17:34:57
---------------
20% complete. Time elapsed: 4.2 min
Estimated finish time: 07/13/21:17:34:52
---------------
21% complete. Time elapsed: 4.4 min
Estimated finish time: 07/13/21:17:34:46
---------------
22% complete. Time elapsed: 4.7 min
Estimated finish time: 07/13/21:17:35:00
---------------
23% complete. Time elapsed: 4.9 min
Estimated finish time: 07/13/21:17:35:02
---------------
24% complete. Time elapsed: 5.2 min
Estimated finish time: 07/13/21:17:35:02
---------------
25% complete. Time elapsed: 5.4 min
Estimated finish time: 07/13/21:17:34:59
---------------
26% complete. Time elapsed: 5.6 min
Estimated finish time: 07/13/21:17:34:57
---------------
27% complete. Time elapsed: 5.8 min
Estimated finish time: 07/13/21:17:34:56
---------------
28% complete. Time elapsed: 6.0 min
Estimated finish time: 07/13/21:17:34:55
---------------
29% complete. Time elapsed: 6.2 min
Estimated finish time: 07/13/21:17:34:50
---------------
30% complete. Time elapsed: 6.4 min
Estimated finish time: 07/13/21:17:34:51
---------------
31% complete. Time elapsed: 6.6 min
Estimated finish time: 07/13/21:17:34:49
---------------
32% complete. Time elapsed: 6.8 min
Estimated finish time: 07/13/21:17:34:49
---------------
33% complete. Time elapsed: 7.1 min
Estimated finish time: 07/13/21:17:34:53
---------------
34% complete. Time elapsed: 7.3 min
Estimated finish time: 07/13/21:17:34:52
---------------
35% complete. Time elapsed: 7.5 min
Estimated finish time: 07/13/21:17:34:50
---------------
36% complete. Time elapsed: 7.7 min
Estimated finish time: 07/13/21:17:34:47
---------------
37% complete. Time elapsed: 7.9 min
Estimated finish time: 07/13/21:17:34:48
---------------
38% complete. Time elapsed: 8.1 min
Estimated finish time: 07/13/21:17:34:45
---------------
39% complete. Time elapsed: 8.3 min
Estimated finish time: 07/13/21:17:34:43
---------------
40% complete. Time elapsed: 8.5 min
Estimated finish time: 07/13/21:17:34:43
---------------
41% complete. Time elapsed: 8.8 min
Estimated finish time: 07/13/21:17:34:45
---------------
42% complete. Time elapsed: 9.0 min
Estimated finish time: 07/13/21:17:34:45
---------------
43% complete. Time elapsed: 9.2 min
Estimated finish time: 07/13/21:17:34:46
---------------
44% complete. Time elapsed: 9.4 min
Estimated finish time: 07/13/21:17:34:45
---------------
45% complete. Time elapsed: 9.7 min
Estimated finish time: 07/13/21:17:34:48
---------------
46% complete. Time elapsed: 9.9 min
Estimated finish time: 07/13/21:17:34:47
---------------
47% complete. Time elapsed: 10.1 min
Estimated finish time: 07/13/21:17:34:45
---------------
48% complete. Time elapsed: 10.3 min
Estimated finish time: 07/13/21:17:34:46
---------------
49% complete. Time elapsed: 10.5 min
Estimated finish time: 07/13/21:17:34:48
---------------
50% complete. Time elapsed: 10.8 min
Estimated finish time: 07/13/21:17:34:52
---------------
51% complete. Time elapsed: 11.0 min
Estimated finish time: 07/13/21:17:34:53
---------------
52% complete. Time elapsed: 11.2 min
Estimated finish time: 07/13/21:17:34:55
---------------
53% complete. Time elapsed: 11.5 min
Estimated finish time: 07/13/21:17:34:57
---------------
54% complete. Time elapsed: 11.7 min
Estimated finish time: 07/13/21:17:34:58
---------------
55% complete. Time elapsed: 12.0 min
Estimated finish time: 07/13/21:17:35:01
---------------
56% complete. Time elapsed: 12.2 min
Estimated finish time: 07/13/21:17:35:02
---------------
57% complete. Time elapsed: 12.4 min
Estimated finish time: 07/13/21:17:35:03
---------------
58% complete. Time elapsed: 12.7 min
Estimated finish time: 07/13/21:17:35:09
---------------
59% complete. Time elapsed: 13.0 min
Estimated finish time: 07/13/21:17:35:13
---------------
60% complete. Time elapsed: 13.2 min
Estimated finish time: 07/13/21:17:35:17
---------------
61% complete. Time elapsed: 13.5 min
Estimated finish time: 07/13/21:17:35:23
---------------
62% complete. Time elapsed: 13.8 min
Estimated finish time: 07/13/21:17:35:30
---------------
63% complete. Time elapsed: 14.1 min
Estimated finish time: 07/13/21:17:35:34
---------------
64% complete. Time elapsed: 14.3 min
Estimated finish time: 07/13/21:17:35:37
---------------
65% complete. Time elapsed: 14.6 min
Estimated finish time: 07/13/21:17:35:41
---------------
66% complete. Time elapsed: 14.9 min
Estimated finish time: 07/13/21:17:35:48
---------------
67% complete. Time elapsed: 15.1 min
Estimated finish time: 07/13/21:17:35:52
---------------
68% complete. Time elapsed: 15.4 min
Estimated finish time: 07/13/21:17:35:56
---------------
69% complete. Time elapsed: 15.7 min
Estimated finish time: 07/13/21:17:35:59
---------------
70% complete. Time elapsed: 16.0 min
Estimated finish time: 07/13/21:17:36:06
---------------
71% complete. Time elapsed: 16.2 min
Estimated finish time: 07/13/21:17:36:08
---------------
72% complete. Time elapsed: 16.5 min
Estimated finish time: 07/13/21:17:36:11
---------------
73% complete. Time elapsed: 16.8 min
Estimated finish time: 07/13/21:17:36:14
---------------
74% complete. Time elapsed: 17.1 min
Estimated finish time: 07/13/21:17:36:19
---------------
75% complete. Time elapsed: 17.3 min
Estimated finish time: 07/13/21:17:36:19
---------------
76% complete. Time elapsed: 17.6 min
Estimated finish time: 07/13/21:17:36:21
---------------
77% complete. Time elapsed: 17.8 min
Estimated finish time: 07/13/21:17:36:24
---------------
78% complete. Time elapsed: 18.1 min
Estimated finish time: 07/13/21:17:36:29
---------------
79% complete. Time elapsed: 18.4 min
Estimated finish time: 07/13/21:17:36:31
---------------
80% complete. Time elapsed: 18.7 min
Estimated finish time: 07/13/21:17:36:33
---------------
81% complete. Time elapsed: 18.9 min
Estimated finish time: 07/13/21:17:36:34
---------------
82% complete. Time elapsed: 19.2 min
Estimated finish time: 07/13/21:17:36:39
---------------
83% complete. Time elapsed: 19.5 min
Estimated finish time: 07/13/21:17:36:40
---------------
84% complete. Time elapsed: 19.7 min
Estimated finish time: 07/13/21:17:36:39
---------------
85% complete. Time elapsed: 19.9 min
Estimated finish time: 07/13/21:17:36:37
---------------
86% complete. Time elapsed: 20.1 min
Estimated finish time: 07/13/21:17:36:38
---------------
87% complete. Time elapsed: 20.3 min
Estimated finish time: 07/13/21:17:36:36
---------------

88% complete. Time elapsed: 20.5 min
Estimated finish time: 07/13/21:17:36:34
---------------
89% complete. Time elapsed: 20.7 min
Estimated finish time: 07/13/21:17:36:30
---------------
90% complete. Time elapsed: 21.0 min
Estimated finish time: 07/13/21:17:36:31
---------------
91% complete. Time elapsed: 21.2 min
Estimated finish time: 07/13/21:17:36:32
---------------
92% complete. Time elapsed: 21.4 min
Estimated finish time: 07/13/21:17:36:31
---------------
93% complete. Time elapsed: 21.7 min
Estimated finish time: 07/13/21:17:36:30
---------------
94% complete. Time elapsed: 21.9 min
Estimated finish time: 07/13/21:17:36:32
---------------
95% complete. Time elapsed: 22.1 min
Estimated finish time: 07/13/21:17:36:30
---------------
96% complete. Time elapsed: 22.3 min
Estimated finish time: 07/13/21:17:36:27
---------------
97% complete. Time elapsed: 22.5 min
Estimated finish time: 07/13/21:17:36:25
---------------
98% complete. Time elapsed: 22.8 min
Estimated finish time: 07/13/21:17:36:27
---------------
99% complete. Time elapsed: 23.0 min
Estimated finish time: 07/13/21:17:36:26
---------------
100% complete. Time elapsed: 23.2 min
Estimated finish time: 07/13/21:17:36:24
---------------
-------------------------
Finished. That took 23.3 min.
Actual finish time: 17:36:24

In [142]:
final_table

,tweet,0,1,2,3,4,5,6,7,8,...,10,11,12,13,14,15,16,17,18,19
0,!!! RT @mayasolovely: As a woman you shouldn't...,0.010742,-0.004391,0.015802,-0.003414,0.003390,0.003548,-0.003043,-0.002796,-0.001108,...,-0.000829,0.012718,0.006761,-0.006497,-0.012051,0.007794,-0.009507,0.006585,0.005737,-0.001666
1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...,0.004841,0.004436,0.000914,-0.009751,0.005038,0.011150,0.011603,0.009655,-0.012505,...,0.004664,0.002429,0.014794,0.004940,0.001413,-0.004927,0.012201,0.005936,-0.018094,0.001071
2,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...,0.008423,0.012927,0.011020,0.010654,0.000597,-0.006037,0.007699,0.020504,-0.008069,...,-0.005035,-0.017148,0.020670,0.006083,-0.009244,-0.002631,0.001638,-0.007432,-0.004601,-0.016549
3,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...,0.018069,-0.003312,0.002020,-0.004119,0.017109,-0.017962,0.002340,0.022885,0.002644,...,0.005931,-0.010217,0.019906,-0.022391,0.001863,0.004285,0.007125,-0.005956,0.020242,-0.004850
4,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...,-0.009344,0.005417,-0.008419,0.004743,0.009811,-0.017030,0.007335,0.005161,-0.005933,...,0.005729,-0.005238,-0.000171,-0.005781,-0.016183,-0.009473,0.009901,-0.018340,0.006494,-0.018538
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24778,you's a muthaf***in lie &#8220;@LifeAsKing: @2...,-0.003729,-0.017738,0.009045,-0.016504,-0.010244,-0.000089,0.005051,0.001840,0.020293,...,-0.001044,0.008122,0.019703,0.007250,-0.005047,0.009291,0.010963,-0.000282,-0.033845,-0.003717
24779,"you've gone and broke the wrong heart baby, an...",0.002734,-0.002392,0.011020,-0.018769,-0.008788,0.001414,0.003678,0.012647,0.002893,...,0.001392,-0.001854,-0.005640,-0.003610,0.009778,0.003094,-0.006933,0.004517,-0.003791,-0.002358
24780,young buck wanna eat!!.. dat nigguh like I ain...,0.006171,-0.002461,-0.018769,-0.001899,-0.009897,-0.001166,-0.000997,0.009243,-0.004765,...,0.022077,-0.010136,0.003253,0.004180,-0.009084,0.002988,0.000453,-0.005204,0.001637,0.012166
24781,youu got wild bitches tellin you lies,-0.032547,-0.003426,-0.006520,0.006167,0.011983,-0.023309,0.006597,0.013260,-0.012604,...,0.008047,-0.002982,-0.004045,0.015829,0.015913,-0.007844,0.015752,-0.005909,-0.016210,-0.011625
24782,~~Ruffled | Ntac Eileen Dahlia - Beautiful col...,-0.008228,0.011358,-0.002688,0.015407,-0.005419,-0.005906,-0.004368,0.005869,0.005959,...,0.012390,0.005775,-0.000302,-0.000601,0.003413,0.008001,0.002741,0.001170,-0.000338,-0.013942

In [133]:
removed_comments

Empty DataFrame
Columns: [tweet]
Index: []

In [123]:
df = pd.read_csv('labeled_data.csv')

In [124]:
df

,Unnamed: 0,count,hate_speech,offensive_language,neither,class,tweet
0,0,3,0,0,3,2,!!! RT @mayasolovely: As a woman you shouldn't...
1,1,3,0,3,0,1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2,2,3,0,3,0,1,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3,3,3,0,2,1,1,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4,4,6,0,6,0,1,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...
...,...,...,...,...,...,...,...
24778,25291,3,0,2,1,1,you's a muthaf***in lie &#8220;@LifeAsKing: @2...
24779,25292,3,0,1,2,2,"you've gone and broke the wrong heart baby, an..."
24780,25294,3,0,3,0,1,young buck wanna eat!!.. dat nigguh like I ain...
24781,25295,6,0,6,0,1,youu got wild bitches tellin you lies
24782,25296,3,0,0,3,2,~~Ruffled | Ntac Eileen Dahlia - Beautiful col...